# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
  db:
    container_name: "mysql"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  api:
    container_name: "api"
    image: api
    depends_on:
      - db
      - redis_image
    restart: always
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"

  redis_image:
    container_name: "redis"
    image: redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
